apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
data:
  appName: {{ .Values.config.appName | quote }}
  environment: {{ .Values.config.environment | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
