{{- if and .Values.modules.scheduling .Values.modules.scheduling.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}-scheduling-068
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduling
data:
  module: "scheduling"
  sampleId: "68"
  description: "Sample configmap for scheduling module - template 68"
{{- end }}
