{{- if and .Values.modules.notifications .Values.modules.notifications.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}-notifications-095
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
data:
  module: "notifications"
  sampleId: "95"
  description: "Sample configmap for notifications module - template 95"
{{- end }}
