{{- if and .Values.modules.security .Values.modules.security.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}-security-079
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
data:
  module: "security"
  sampleId: "79"
  description: "Sample configmap for security module - template 79"
{{- end }}
