{{- if and .Values.modules.storage .Values.modules.storage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}-storage-106
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
data:
  module: "storage"
  sampleId: "106"
  description: "Sample configmap for storage module - template 106"
{{- end }}
