{{- if and .Values.modules.auth .Values.modules.auth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "large-chart.fullname" . }}-auth-094
  labels:
    {{- include "large-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
data:
  module: "auth"
  sampleId: "94"
  description: "Sample configmap for auth module - template 94"
{{- end }}
